### ISSUE TITLE
help and/or issues

### ISSUE THREAD

**Issue by HumanG33k** [Blackdread/canon-sdk-java#15] opened 2019-03-31 14:40 UTC
Hello, 

I try to make the sdk working in an java/javafx project. I final goal isto show the camera preview, take a picture and import it on the computer. 

I work with a netbeans project. The project is a maven project and i put this on the pom 

```xml
        <!-- https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter-api -->
        <!-- For test class -->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>5.5.0-M1</version>
            <type>jar</type>
        </dependency>        
        <!-- https://mvnrepository.com/artifact/org.blackdread/camera-binding -->
<dependency>
    <groupId>org.blackdread</groupId>
    <artifactId>camera-binding</artifactId>
    <version>1.1.4</version>
</dependency>
<!-- https://mvnrepository.com/artifact/org.blackdread/canon-sdk-java -->
<dependency>
    <groupId>org.blackdread</groupId>
    <artifactId>canon-sdk-java</artifactId>
    <version>1.1.4</version>
    <type>pom</type>
</dependency>
<!-- https://mvnrepository.com/artifact/org.blackdread/camera-framework -->
<dependency>
    <groupId>org.blackdread</groupId>
    <artifactId>camera-framework</artifactId>
    <version>1.1.4</version>
</dependency>
```
I create a standard javafxml main  class and try to use some code from the demo directory.

Some code can be useless for my trouble you can skip it if i miss to remove it.

```java
import java.util.List;
import java.util.concurrent.ExecutionException;
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;
import javafx.fxml.JavaFXBuilderFactory;

import org.blackdread.camerabinding.jna.EdsdkLibrary;
import org.blackdread.cameraframework.api.camera.CameraManager;
import org.blackdread.cameraframework.api.camera.CanonCamera;
import org.blackdread.cameraframework.api.command.CanonCommand;
import org.blackdread.cameraframework.api.command.TerminateSdkCommand;
import org.blackdread.cameraframework.api.constant.EdsISOSpeed;
import org.blackdread.cameraframework.api.constant.EdsSaveTo;
import org.blackdread.cameraframework.api.helper.factory.CanonFactory;
import org.blackdread.cameraframework.api.helper.initialisation.FrameworkInitialisation;
import org.blackdread.cameraframework.api.helper.logic.event.CameraAddedListener;
import org.blackdread.cameraframework.api.helper.logic.event.CameraObjectListener;
import org.blackdread.cameraframework.api.helper.logic.event.CameraPropertyListener;
import org.blackdread.cameraframework.api.helper.logic.event.CameraStateListener;
import org.junit.jupiter.api.Assertions;


public class Launcher extends Application {
 

    private CameraAddedListener cameraAddedListener;
    private CameraObjectListener cameraObjectListener;
    private CameraPropertyListener cameraPropertyListener;
   private CameraStateListener cameraStateListener;
    
  
    public static void main(String[] args) {
        launch(args);
    }
    @Override
    public void start(Stage primaryStage) {

        this.camTest();
        
      }

    private void camTest()
    {
        cameraAddedListener = event -> {
            System.out.println("Camera added detected: "+ event);
        };
        cameraObjectListener = event -> {
            System.out.println("Object event: "+ event);
        };
        cameraPropertyListener = event -> {
            System.out.println("Property event: "+ event);
        };
        cameraStateListener = event -> {
            System.out.println("State event: "+ event);
        };
        new FrameworkInitialisation()
            .registerCameraAddedEvent()
            .withEventFetcherLogic()
            .withCameraAddedListener(cameraAddedListener)
            .initialize();

        final List<CanonCamera> cameras = CameraManager.getAllCameras();

        Assertions.assertFalse(cameras.isEmpty());

        final CanonCamera camera = cameras.get(0);

        final EdsdkLibrary.EdsCameraRef edsCameraRef = get(camera.openSession());
//        camera.setCameraRef(edsCameraRef); // not necessary as by default on success the ref is set by the openSession command

        // optional as manager does it
        get(camera.getEvent().registerObjectEventCommand());
        get(camera.getEvent().registerPropertyEventCommand());
        get(camera.getEvent().registerStateEventCommand());

        CanonFactory.cameraObjectEventLogic().addCameraObjectListener(cameraObjectListener);
        CanonFactory.cameraPropertyEventLogic().addCameraPropertyListener(edsCameraRef, cameraPropertyListener);
        CanonFactory.cameraStateEventLogic().addCameraStateListener(edsCameraRef, cameraStateListener);

        final String artist = get(camera.getProperty().getArtistAsync());
        System.out.println("artist: "+ artist);

        final String serial = get(camera.getProperty().getBodyIDExAsync());
        System.out.println("serial: "+ serial);

        final EdsISOSpeed isoSpeed = get(camera.getProperty().getIsoSpeedAsync());
        System.out.println("isoSpeed: "+ isoSpeed);

        final EdsSaveTo saveTo = get(camera.getProperty().getSaveToAsync());
        System.out.println("saveTo: "+ saveTo);

        get(camera.closeSession());

CanonFactory.commandDispatcher().scheduleCommand(new TerminateSdkCommand());

    }
    
    

    private static <R> R get(final CanonCommand<R> command) {
        try {
            return command.get();
        } catch (InterruptedException | ExecutionException e) {
            throw new IllegalStateException(e);
        }
    }
    
   
}
```

When i build there is no trouble but when i run i add this error : 
```
[cmd-dispatcher-0] INFO org.blackdread.cameraframework.api.helper.factory.CanonLibraryImpl - Dll auto selected to 32 bit
[cmd-dispatcher-0] WARN org.blackdread.cameraframework.api.helper.factory.SingleCommandDispatcher - Command dispatcher thread ended
Exception in thread "cmd-dispatcher-0" java.lang.Error: Le chemin d’accès spécifié est introuvable. // This means the specify path can't be found

	at com.sun.jna.Native.open(Native Method)
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:171)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:398)
	at com.sun.jna.Library$Handler.<init>(Library.java:147)
	at com.sun.jna.Native.loadLibrary(Native.java:412)
	at org.blackdread.cameraframework.api.helper.factory.CanonLibraryImpl.initLibrary(CanonLibraryImpl.java:150)
	at org.blackdread.cameraframework.api.helper.factory.CanonLibraryImpl.edsdkLibrary(CanonLibraryImpl.java:95)
	at org.blackdread.cameraframework.api.helper.factory.CanonFactory.edsdkLibrary(CanonFactory.java:155)
	at org.blackdread.cameraframework.api.command.InitializeSdkCommand.runInternal(InitializeSdkCommand.java:50)
	at org.blackdread.cameraframework.api.command.InitializeSdkCommand.runInternal(InitializeSdkCommand.java:39)
	at org.blackdread.cameraframework.api.command.AbstractCanonCommand.run(AbstractCanonCommand.java:131)
	at org.blackdread.cameraframework.api.helper.factory.SingleCommandDispatcher.commandDispatcher(SingleCommandDispatcher.java:152)
	at java.lang.Thread.run(Thread.java:748)
```

I translate the error message. I think it can come from several sources (but maybe from an other)
- the path for the sdk i provide is wrong (i put it on the netbeans project ressource directory) 
- the code need class it can't be reach, i can t use some classes like IsConnected or DllOnPath.

Thx for your help.

**Comment by Blackdread** [comment] 2019-03-31 14:47
Hi, does [this](https://github.com/Blackdread/canon-sdk-java/tree/master/camera-framework#library-path-during-development) help?

**Comment by HumanG33k** [comment] 2019-03-31 15:07
No, 
A little thing but i don't think is the cause. 
The computer is a amd64 but the windows version runnig is a 32bit. (i use what people provide me ...)

**Comment by Blackdread** [comment] 2019-03-31 15:14
Check the [CanonLibraryImpl](https://github.com/Blackdread/canon-sdk-java/blob/master/camera-framework/src/main/java/org/blackdread/cameraframework/api/helper/factory/CanonLibraryImpl.java) class as the exception comes from there.

As you said you have a amd64 but a 32bit windows, so the library has auto-selected the path to library (DLL) for 32bit PCs (but that is not the issue here).

My guess is the DLL are not found so there are not placed in the correct folder given by

- DEFAULT_LIB_32_PATH (the one used in your case)
- DEFAULT_LIB_64_PATH

**Comment by HumanG33k** [comment] 2019-03-31 15:41
This is the command use by netbeans.
```
cd C:\Users\user\Documents\test\projet\test; "JAVA_HOME=C:\\Program Files\\Java\\jdk1.8.0_202" cmd /c "\"\"C:\\Program Files\\NetBeans 8.2\\java\\maven\\bin\\mvn.bat\" -Dexec.args=\"-classpath %classpath Launcher\" -Dexec.executable=\"C:\\Program Files\\Java\\jdk1.8.0_202\\bin\\java.exe\" -Dexec.workingdir=C:\\Users\\user\\Documents\\test\\projet\\test\\src\\main\\resources -Dmaven.ext.class.path=\"C:\\Program Files\\NetBeans 8.2\\java\\maven-nblib\\netbeans-eventspy.jar\" org.codehaus.mojo:exec-maven-plugin:1.2.1:exec\""
Running NetBeans Compile On Save execution. Phase execution is skipped and output directories of dependency projects (with Compile on Save turned on) will be used instead of their jar artifacts.
```
I currently use the EDSDKv130910W . 

Even after i put files on resources,on the root project, on the jar file directories the error occur.

**Comment by Blackdread** [comment] 2019-03-31 15:48
> on the root project
Also in root folder of camera-framework module?

My root project folder is "canon-sdk-java" but the module of framework is "camera-framework", it is in "camera-framework" folder that library folders should be put.

I see you are using java 8 so no problem (I have not tested java 11 yet with the framework).

PS: I am working on a project to create a software for controlling/preview/etc camera with JavaFx, I will provide more on it later.
But I have not the issue you have right now, I can control, shoot, set params, etc using runtime of IntelliJ IDEA and also jar with Maven package.

**Comment by HumanG33k** [comment] 2019-03-31 16:18
So i put Dll directories on the "camera-framework" directory "C:\Users\user\.m2\repository\org\blackdread\camera-framework" for me. (for next readers i find it in doing a right click on camera-framework-1.1.4.jar and choose copy location, in dependencies section in project panel)

Maybe i should just say f*ck *ff to the maven dependency, git clone build the jar myself and add it as local dependency ?

**Comment by Blackdread** [comment] 2019-04-01 02:44
I do not use NetBeans but that should not be an issue, Eclipse is good as well (Free).

Maven dependency is a good thing.

When I said "camera-framework", it is not the maven local repository but the source code cloned folder -> I see a ".m2" in your path so I guess you put in local maven repo.

The problem is your runtime does not find the "EDSDK\Dll\EDSDK.dll" library.

**Comment by HumanG33k** [comment] 2019-04-03 13:30
I fix it. There is several ways to add it.
- The good way, is to add it system side (/usr/lib, C:/windows/system32 etc)
- The bad way in the working/compiling/project folder/path

Maven is not as good as you think. For example it's easy for dev to forget to maintain his project dependancies.

What is your advice to manage exception from your lib ?
I just check your demo for live preview. 
You just save picture right. I try to use it but for display in an imageview but it's not working do you achieve it in your javafx project ? 

for reminder
```java
for (int i = 0; i < 10; i++) {
                final BufferedImage bufferedImage = get(camera.getLiveView().downloadLiveViewAsync());
                // if try to download too quick live view then will get "EDS_ERR_OBJECT_NOTREADY"
                Thread.sleep(200);

                final int tempI = i;
                CompletableFuture.runAsync(() -> {
                    try {
                        ImageIO.write(bufferedImage, "jpeg", new File("target/image-" + tempI + ".jpg"));
                    } catch (IOException e) {
                        throw new IllegalStateException(e);
                    }
                });
}
```
I use a while loop 

```java
      this.window = MainApp.getInstance().getWindow();
       this.core.initCam();
       while(!stopCamera){
        BufferedImage livePreIm = this.core.fullLiveDemo();
        
          if(livePreIm != null){
            System.out.println("Prepare the image to be load by preview");
            Image image = SwingFXUtils.toFXImage(livePreIm, null);
            this.livePre = (ImageView) window.getScene().lookup("#livePre");
            this.livePre.setImage(image);
            this.livePre.setPreserveRatio(true);
            System.out.println("Show the new scene");

        }else{
            stopCamera = true;
        }
        
       }
       this.core.closeCam();
```
but it's not working at this point.

**Comment by Blackdread** [comment] 2019-04-03 15:27
Yes I achieved to do it in my app (and using ImageView as well).

It is difficult to help without seeing all code you use like : 
- how you init your camera
- is your camera connected
- which command you use to get liveview image
- etc

About errors you put:
- First one with CameraManager
This error is normal, it is in INFO level, it happens when framework test if camera is already connected with an open session or not. If not then it will open and provide you a new camera instance.

- EdsdkPictureWriteCardErrorException
Seems that it cannot write to your SD card, do you have one in camera?
If yes, maybe it is in READ-ONLY mode (but should get EDS_ERR_TAKE_PICTURE_CARD_PROTECT_NG error instead).
Or the shoot option is not used well with the SaveTo, you might not want to save at all the image on camera but only PC (so use events to directly download images and save on PC)

- Last: No native enum found for value 16778275 for enum EdsPropertyID
Some possible values may be missing from framework, I put all values that were given in headers files of version 3.9.0 (and some older ones).
Those unknown values need to be found in different version of EDSDK then I can add them so it would not throw anymore.
For my project I have defined different commands to handle that, some GET commands simply catch that exception and continue next values when doing DESC. I do not provide those commands right now in framework as I prefer to make it strict by default so user can decide by himself if want to loosen some rules.

**Comment by Blackdread** [comment] 2019-04-04 03:36
To use system folder is not the best but it works.
You can use custom path via property "blackdread.cameraframework.library.path", it was made for that kind of issue (can provide absolute path in it).

I also had the issue of library not being found but I got it after updating my version on IntelliJ IDEA which has changed class path used from before, now it search in "target\classes" and "target\test-classes" instead of root folder of module.
I just fixed by moving my library to "new" classpath but I could have fixed by setting extra classpath in config of IntelliJ IDEA, etc.
For pratical use case, I set property "blackdread.cameraframework.library.path" to location I had my DLL

**Comment by HumanG33k** [comment] 2019-04-07 11:22
Nice work 
I’ll create a gist/git with an exemple of what i try to achieve so you will explain me what i doing wrong ;)

**Comment by Blackdread** [comment] 2019-04-18 06:48
I close since no changes

**Closed by Blackdread** 2019-04-18 06:48 UTC

**Comment by testing138** [comment] 2022-08-02 13:11
@HumanG33k  did you fixed that issue?

**Comment by Blackdread** [comment] 2022-08-02 20:12
The project is private and consultancy provided to companies
